# Use custom format
# with multiline basic string
format = """
[â”Œâ”€](bold green)$username$hostname$directory
[â”‚](bold green)
[â””â”€>](bold green)"""

# format = "$all"

# # Which is equivalent to
# format = """
# $username\
# $hostname\
# $shlvl\
# $kubernetes\
# $directory\
# $vcsh\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $hg_branch\
# $docker_context\
# $package\
# $cmake\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $golang\
# $helm\
# $java\
# $julia\
# $kotlin\
# $nim\
# $nodejs\
# $ocaml\
# $perl\
# $php\
# $purescript\
# $python\
# $red\
# $ruby\
# $rust\
# $scala\
# $swift\
# $terraform\
# $vlang\
# $vagrant\
# $zig\
# $nix_shell\
# $conda\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $env_var\
# $crystal\
# $custom\
# $cmd_duration\
# $line_break\
# $lua\
# $jobs\
# $battery\
# $time\
# $status\
# $shell\
# $character"""

# https://starship.rs/config/#prompt
# Disable the blank line at the start of the prompt
# add_newline = false

# https://starship.rs/config/#username
# [username]
# style_user = "blue bold"
# style_root = "black bold"
# format = "[$user]($style)"
# disabled = false
# show_always = true

# https://starship.rs/config/#hostname
# [hostname]
# ssh_only = false
# format =  "[@$hostname](bold red)"
# trim_at = "."
# disabled = false

# https://starship.rs/config/#directory
# [directory]
# truncation_length = 8
# truncation_symbol = "â€¦/"
# truncate_to_repo = false
# use_logical_path = true
# disabled = false

# Replace the "â¯" symbol in the prompt with "@"
# [character]
# success_symbol = "[@](bold green)"
# error_symbol = "[@](bold red)"

# https://starship.rs/config/#python
# [python]
# disabled = true

# https://starship.rs/config/#line-break
# [line_break]
# disabled = false


# https://starship.rs/config/#command-duration
# [cmd_duration]
# min_time = 500
# format = "underwent [$duration](bold yellow)"


# https://starship.rs/config/#time
# [time]
# disabled = false
# format = "at [$time]($style) "
# time_format = "%T"
# utc_time_offset = "-5"
# time_range = "00:00:00-23:59:59"

# https://starship.rs/config/#memory-usage
# [memory_usage]
# disabled = false
# threshold = -1
# symbol = " "
# format = " $symbol [${ram}( \| ${swap})]($style) "
# style = "bold dimmed green"


# https://starship.rs/config/#package-version
# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

# https://starship.rs/config/#status
# [status]
# style = "bg:blue"
# symbol = "ğŸ”´"
# format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
# map_symbol = true
# disabled = false

# https://starship.rs/config/#shell
# [shell]
# fish_indicator = "ïœ¹"
# powershell_indicator = "ï‘ _"
# unknown_indicator = "mystery shell"
# disabled = false

# https://starship.rs/config/#git-state
# [git_state]
# format             = '\([$state($progress_current/$progress_total)]($style)\)'
# rebase             = "REBASING"
# merge              = "MERGING"
# revert             = "REVERTING"
# cherry_pick        = "CHERRY-PICKING"
# bisect             = "BISECTING"
# am                 = "AM"
# am_or_rebase       = "AM/REBASE"
# style              = "bold yellow bg:236"
# disabled           = false

# # https://starship.rs/config/#git-status
# [git_status]
# format             = '([$all_status$ahead_behind]($style)[î‚´](fg:236))'
# style              = "bold white bg:236"
# conflicted         = " =$count"
# ahead              = " â‡¡$count"
# behind             = " â‡£$count"
# diverged           = " [$ahead_count](green)â‡•[$behind_count](red bg:236)"
# untracked          = " [$countï„¨](purple bg:236)"
# stashed            = " $countï…«"
# modified           = " [$countï„ª](yellow bg:236)"
# staged             = " +$count"
# renamed            = " Â»$count"
# deleted            = " [$countâœ˜](red bg:236)"
# disabled           = false

# https://starship.rs/config/#git-status
# [git_status]
# format = '([$all_status$ahead_behind]($style)[î‚´](fg:236))'
# conflicted = " ğŸ³$count"
# ahead = " ğŸğŸ’¨$count"
# behind = " ğŸ˜°$count"
# diverged = " [$ahead_count](green)ğŸ˜µ[$behind_count](red bg:236)"
# untracked = " [$countğŸ¤·](purple bg:236)â€"
# stashed = " $countğŸ“¦"
# modified = " [$countğŸ“](yellow bg:236)"
# staged = ' [++\($count\)](green)'
# renamed = " ğŸ‘…$count"
# deleted = "[$countğŸ—‘](red bg:236)"
# disabled = false

# https://starship.rs/config/#git-status
# [git_status]
# ahead = "â‡¡${count}"
# diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
# behind = "â‡£${count}"
# disabled = false